###
POST http://localhost:8080/api/reservation/reserve
Content-Type: application/json

{
  "seatCode": "1b",
  "userId": 1,
  "guestName": "David",
  "guestMail": "Thomassen@email.dk",
  "showingId": 1
}